In [1]:
import pandas as pd

In [2]:
url = 'https://data.cityofnewyork.us/resource/erm2-nwe9.csv'

In [6]:
limit = 1000

In [7]:
url2 = f'{url}?$limit={limit}'

In [8]:
df = pd.read_csv(url2)

In [11]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,60656072,2024-03-23T02:47:47.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,11216.0,EASTERN PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,60659173,2024-03-23T02:20:56.000,2024-03-23T02:20:56.000,DOT,Department of Transportation,Street Condition,Pothole,NaN,11429.0,211 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,60655090,2024-03-23T01:36:06.000,NaN,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,10462.0,1142 CASTLE HILL AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.830851,-73.850775,"\n, \n(40.83085140810475, -73.850774993076)"
3,60658592,2024-03-23T01:35:33.000,NaN,NYPD,New York City Police Department,Illegal Parking,Overnight Commercial Storage,Street/Sidewalk,11105.0,20 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.782856,-73.910730,"\n, \n(40.78285600733012, -73.91073033113776)"
4,60655111,2024-03-23T01:35:14.000,NaN,NYPD,New York City Police Department,Noise - Commercial,Loud Television,Store/Commercial,10467.0,3518 BAINBRIDGE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.881375,-73.878377,"\n, \n(40.881375390278926, -73.87837687617764)"